project/studyproject/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

project/studyproject/firstapp/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'firstapp'

urlpatterns = [
    # base_views
    path('',
         base_views.index,
         name = 'index'),
    path('<int:question_id>/',
         base_views.detail,
         name = 'detail'),

    # question_views
    path('question/create/',
         question_views.question_create,
         name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify,
         name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete,
         name='question_delete'),

    # answer_views
    path('answer/create/<int:question_id>/',
         answer_views.answer_create,
         name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify,
         name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete,
         name='answer_delete'),

    # comment_views
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question,
         name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question,
         name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question,
         name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer,
         name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer,
         name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer,
         name='comment_delete_answer'),

    # vote_views
    path('vote/question/<int:question_id>/',
         vote_views.vote_question,
         name='vote_question'),
    path('vote/answer/<int:answer_id>/',
         vote_views.vote_answer,
         name='vote_answer'),
]

project/studyproject/studyproject/urls.py
from django.contrib import admin
from django.urls import path, include
from firstapp.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstapp/', include('firstapp.urls')),
    path('account/', include('account.urls')),
    path('',base_views.index, name='index'), # / 페이지에 해당하는 urlpattern
]

project/studyproject/firstapp/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question

def index(request) :
    """
    firstapp 목록 출력
    """
    # 입력 인자
    page = request.GET.get('page','1') #페이지
    kw = request.GET.get('kw', '') #검색창
    sort = request.GET.get('sort', 'recent')

    #정렬
    if sort == 'recommend' :
        question_list = Question.objects.annotate(
            num_voter = Count('voter')).order_by('-num_voter', '-create_date')
    elif sort == 'popular':
        question_list = Question.objects.annotate(
            num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else : #recent (최근순_초기값)
        question_list = Question.objects.order_by('-create_date')

    #조회
    #question_list = Question.objects.order_by('-create_date') [정렬]의 기준 중 하나로 변환
    if kw :
        question_list = question_list.filter(
            Q(subject__icontains=kw)|
            Q(content__icontains=kw)|
            Q(author__username__icontains=kw)|
            Q(answer__author__username__icontains=kw)
        ).distinct()

    #페이지 처리
    paginator = Paginator(question_list, 10) # 페이지당 10개씩 보기 설정
    page_obj = paginator.get_page(page)

    context = {'question_list' : page_obj, #paginator를 통해 페이지 번호와 보기 개수까지 받기
               'page' : page, 'kw' : kw,
               'sort' : sort}
    return render(request, 'firstapp/question_list.html', context)

def detail(request, question_id) :
    """
    firstapp 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'firstapp/question_detail.html', context)

project/studyproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- firstapp CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, app!</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!--jQuery JS-->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!--Bootstrap JS-->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!--자바스크립트 Start-->
{% block script %}
{% endblock %}
<!--자바스크립트 End-->
</body>
</html>

project/studyproject/templates/forms_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

project/studyproject/templates/navbar.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

<!--네비게이션 바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'firstapp:index' %}">First App</a>
    <button class="navbar-toggle ml-auto" type="button" data-toggle="collapse"
       data-target="#navbarNav" aria-controls="navbarNav"
       aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'account:logout' %}">
                    {{ user.username }} (로그아웃)
                </a>
                {% else %}
                <a class="nav-link" href="{% url 'account:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>