project/studyproject/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

project/studyproject/firstapp/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'firstapp'

urlpatterns = [
    # base_views
    path('',
         base_views.index,
         name = 'index'),
    path('<int:question_id>/',
         base_views.detail,
         name = 'detail'),

    # question_views
    path('question/create/',
         question_views.question_create,
         name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify,
         name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete,
         name='question_delete'),

    # answer_views
    path('answer/create/<int:question_id>/',
         answer_views.answer_create,
         name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify,
         name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete,
         name='answer_delete'),

    # comment_views
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question,
         name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question,
         name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question,
         name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer,
         name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer,
         name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer,
         name='comment_delete_answer'),

    # vote_views
    path('vote/question/<int:question_id>/',
         vote_views.vote_question,
         name='vote_question'),
    path('vote/answer/<int:answer_id>/',
         vote_views.vote_answer,
         name='vote_answer'),
]

project/studyproject/studyproject/urls.py
from django.contrib import admin
from django.urls import path, include
from firstapp.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstapp/', include('firstapp.urls')),
    path('account/', include('account.urls')),
    path('',base_views.index, name='index'), # / 페이지에 해당하는 urlpattern
]

project/studyproject/firstapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model) :
    #계정/사용자명
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author_question')
    #질문의 제목
    subject = models.CharField(max_length=200)
    #질문의 내용
    content = models.TextField()
    #작성 일시
    create_date = models.DateTimeField()
    #수정 일시
    modify_date = models.DateTimeField(null=True, blank=True)
    #추천
    voter = models.ManyToManyField(User,
                                   related_name='voter_questiion')
    def __str__(self):
        return self.subject

class Answer(models.Model) :
    # 계정/사용자명
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author_answer')
    #특정 질문의 답변
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    #답변의 내용
    content = models.TextField()
    #작성 일시
    create_date = models.DateTimeField()
    #수정 일시
    modify_date = models.DateTimeField(null=True, blank=True)
    #추천
    voter = models.ManyToManyField(User,
                                   related_name='voter_answer')


class Comment(models.Model) :
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True,
                                 on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

# Create your models here.

project/studyproject/firstapp/forms.py
from django import forms
from firstapp.models import Question, Answer, Comment

class QuestionForm(forms.ModelForm) :
    class Meta :
        model = Question
        fields = ['subject', 'content']
        #widget 삭제
        labels = {
            'subject' : '제목',
            'content' : '내용',
        }

class AnswerForm(forms.ModelForm) :
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

class  CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content' : '댓글내용',
        }

project/studyproject/firstapp/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='account:login')
def answer_create(request, question_id) :
    """
    firstapp 답변 등록
    """
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST" :
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('firstapp:detail', question_id=question.id),answer.id))
    else :
        form = AnswerForm()
    context = {'question' : question, 'form' : form}
    return render(request, 'firstapp/question_detail.html', context)

    #방법1_Answer모델을 통해 데이터 저장
    '''
    answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
    answer.save()
    '''
    # #방법2
    # question.answer_set.create(content=request.POST.get('content'),
    #                            create_date=timezone.now())
    # #등록 후 등록한 값을 포함하여 되돌아가기 (표시하는 코드는 HTML파일에서)
    # return redirect('firstapp:detail', question_id=question_id)

@login_required(login_url='account:login')
def answer_modify(request, answer_id) :
    """
    앱 답변 수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('firstapp:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now() #수정 일시 저장
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('firstapp:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer':answer,'form': form}
    return render(request, 'firstapp/answer_form.html', context)

@login_required(login_url='account:login')
def answer_delete(request, answer_id) :
    """
    답변 삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한 없음')
    else :
        answer.delete()
    return redirect('firstapp:detail', question_id=answer.question.id)

project/studyproject/firstapp/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question

def index(request) :
    """
    firstapp 목록 출력
    """
    # 입력 인자
    page = request.GET.get('page','1') #페이지
    kw = request.GET.get('kw', '') #검색창
    sort = request.GET.get('sort', 'recent')

    #정렬
    if sort == 'recommend' :
        question_list = Question.objects.annotate(
            num_voter = Count('voter')).order_by('-num_voter', '-create_date')
    elif sort == 'popular':
        question_list = Question.objects.annotate(
            num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else : #recent (최근순_초기값)
        question_list = Question.objects.order_by('-create_date')

    #조회
    #question_list = Question.objects.order_by('-create_date') [정렬]의 기준 중 하나로 변환
    if kw :
        question_list = question_list.filter(
            Q(subject__icontains=kw)|
            Q(content__icontains=kw)|
            Q(author__username__icontains=kw)|
            Q(answer__author__username__icontains=kw)
        ).distinct()

    #페이지 처리
    paginator = Paginator(question_list, 10) # 페이지당 10개씩 보기 설정
    page_obj = paginator.get_page(page)

    context = {'question_list' : page_obj, #paginator를 통해 페이지 번호와 보기 개수까지 받기
               'page' : page, 'kw' : kw,
               'sort' : sort}
    return render(request, 'firstapp/question_list.html', context)

def detail(request, question_id) :
    """
    firstapp 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'firstapp/question_detail.html', context)

project/studyproject/firstapp/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Question, Answer, Comment


@login_required(login_url='account:login')
def comment_create_question(request, question_id):
    """
    앱 질문(Question) 댓글 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author=request.user
            comment.create_date=timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('firstapp:detail', question_id=comment.question.id), comment.id))
    else :
        form = CommentForm()
    context = {'form' : form}
    return render(request, 'firstapp/comment_form.html', context)

@login_required(login_url='account:login')
def comment_modify_question(request, comment_id) :
    """
    앱 질문(Question) 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('firstapp:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now() #수정 일시 저장
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('firstapp:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'firstapp/comment_form.html', context)


@login_required(login_url='account:login')
def comment_delete_question(request, comment_id) :
    """
    앱 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한 없음')
        return redirect('firstapp:detail', question_id=comment.question_id)
    else :
        comment.delete()
    return redirect('firstapp:detail', question_id=comment.question_id)


@login_required(login_url='account:login')
def comment_create_answer(request, answer_id):
    """
    앱 답변(Answer) 댓글 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author=request.user
            comment.create_date=timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('firstapp:detail', question_id=comment.answer.question.id), comment.id))
            # comment 모델의 answer모델 내에도 question이 상속되어 있기 때문에
    else :
        form = CommentForm()
    context = {'form' : form}
    return render(request, 'firstapp/comment_form.html', context)

@login_required(login_url='account:login')
def comment_modify_answer(request, comment_id) :
    """
    앱 답변(Answer) 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('firstapp:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now() #수정 일시 저장
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('firstapp:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'firstapp/comment_form.html', context)


@login_required(login_url='account:login')
def comment_delete_answer(request, comment_id) :
    """
    앱 답변(Answer) 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한 없음')
        return redirect('firstapp:detail', question_id=comment.answer.question.id)
    else :
        comment.delete()
    return redirect('firstapp:detail', question_id=comment.answer.question.id)

project/studyproject/firstapp/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question

@login_required(login_url='account:login')
def question_create(request) :
    """
    firstapp 질문 등록
    """
    # 입력데이터 저장 코드
    if request.method == 'POST' :
        form = QuestionForm(request.POST)
        if form.is_valid() :
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return  redirect('firstapp:index')
    else :
        form = QuestionForm()
    context = {'form' : form}
    return render(request, 'firstapp/question_form.html', context)


@login_required(login_url='account:login')
def question_modify(request, question_id) :
    """
    앱 질문 수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('firstapp:detail', question_id=question_id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now() #수정 일시 저장
            question.save()
            return redirect('firstapp:detail', question_id = question_id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'firstapp/question_form.html', context)


@login_required(login_url='account:login')
def question_delete(request, question_id) :
    """
    질문 삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한 없음')
        return redirect('firstapp:detail', question_id=question_id)
    question.delete()
    return redirect('firstapp:index')

project/studyproject/firstapp/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect


from ..models import Question, Answer

@login_required(login_url='account:login')
def vote_question(request, question_id) :
    """
    앱 질문 추천 기능
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author :
        messages.error(request, '본인의 질문은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('firstapp:detail', question_id=question.id)

@login_required(login_url='account:login')
def vote_answer(request, answer_id) :
    """
    앱 답변 추천 기능
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author :
        messages.error(request, '본인의 답변은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('firstapp:detail', question_id=answer.question.id)

project/studyproject/templates/firstapp/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class ='container my-3'>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {% include "forms_errors.html" %}
        <div class="form-group">
            <label for="content">답변 내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

project/studyproject/templates/firstapp/comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글 등록</h5>
    <form method="POST" class="post-form my-3">
        {% csrf_token %}
        {% include "forms_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

project/studyproject/templates/firstapp/question_detail.html
{% extends 'base.html' %}
{% load firstapp_filter %}
{% block content %}
<!-- 상속 전 코드
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
-->
    <!-- 인터프리터 형식이기 때문에 되돌아온 값을 표시하려면 입력 Form보다 위에 위치해야함. -->

<div class="container my-3">
    <!--사용자 오류(추천 오류)-->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"><!--추천기능 구역-->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{ question.voter.count }}
            </div>
            <!--추천버튼-->
            <a href="#" data-uri="{% url 'firstapp:vote_question' question.id %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">
            <!--기존-->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">
                        {{ question.content|mark }}
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">{{ question.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="{% url 'firstapp:question_modify' question.id %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                           data-uri="{% url 'firstapp:question_delete' question.id %}">삭제</a>
                    </div>
                    {% endif %}
                    <!--질문(Question) 댓글 기능-->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in question.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space:pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'firstapp:comment_modify_question' comment.id %}"
                               class="small">수정</a>
                            <a href="#" class="small delete"
                               data-uri="{% url 'firstapp:comment_delete_question' comment.id %}">
                                삭제
                            </a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <!--절대적으로 보이는 '댓글 추가..' 링크-->
                    <div>
                        <a href="{% url 'firstapp:comment_create_question' question.id %}"
                           class="small"><small>댓글 추가..</small></a>
                    </div>
                    <!--질문(Question) 댓글-->
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{answer.id }}"></a><!--마우스 커서 / 화면 스크롤 위치 링크-->
    <div class="row my-3">
        <div class="col-1"><!--추천버튼 영역-->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{ answer.voter.count }}
            </div>
            <!--추천버튼-->
            <a href="#" data-uri="{% url 'firstapp:vote_answer' answer.id %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"><!--답변영역-->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">
                        {{ answer.content|mark }}
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'firstapp:answer_modify' answer.id %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                           data-uri="{% url 'firstapp:answer_delete' answer.id %}">삭제</a>
                    </div>
                    {% endif %}
                    <!--답변(Answer) 댓글 기능-->
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in answer.comment_set.all %}
                        <a name="comment_{{comment.id}}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space:pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'firstapp:comment_modify_answer' comment.id %}"
                               class="small">수정</a>
                            <a href="#" class="small delete"
                               data-uri="{% url 'firstapp:comment_delete_answer' comment.id %}">
                                삭제
                            </a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <!--절대적으로 보이는 '댓글 추가..' 링크-->
                    <div>
                        <a href="{% url 'firstapp:comment_create_answer' answer.id %}"
                           class="small"><small>댓글 추가..</small></a>
                    </div>
                    <!--답변(Answer) 댓글-->
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'firstapp:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert-warning" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content"
                      {% if not user.is_authenticated %}disabled{% endif %}
                      rows="10" class="form-control"></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")){
                location.href = $(this).data('uri');
            }
        });
        $(".recommend").on('click', function(){
            if(confirm("추천하시겠습니까?")){
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

project/studyproject/templates/firstapp/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
<!--        오류표시-->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
<!--            -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}